enum EBuffType
{
	BUFF_Internal = 0,
	BUFF_Aura = 1,
	BUFF_CombatEnchancer = 2,
	BUFF_CombatDehancer = 3,
	BUFF_SpellShield = 4,
	BUFF_Stun = 5,
	BUFF_Invisibility = 6,
	BUFF_Silence = 7,
	BUFF_Taunt = 8,
	BUFF_Polymorph = 9,
	BUFF_Slow = 10,
	BUFF_Snare = 11,
	BUFF_Damage = 12,
	BUFF_Heal = 13,
	BUFF_Haste = 14,
	BUFF_SpellImmunity = 15,
	BUFF_PhysicalImmunity = 16,
	BUFF_Invulnerability = 17,
	BUFF_AttackSpeedSlow = 18,
	BUFF_NearSight = 19,
	BUFF_Currency = 20,
	BUFF_Fear = 21,
	BUFF_Charm = 22,
	BUFF_Poison = 23,
	BUFF_Suppression = 24,
	BUFF_Blind = 25,
	BUFF_Counter = 26,
	BUFF_Shred = 27,
	BUFF_Flee = 28,
	BUFF_Knockup = 29,
	BUFF_Knockback = 30,
	BUFF_Disarm = 31,
	BUFF_Grounded = 32,
	BUFF_Drowsy = 33,
	BUFF_Asleep = 34,
};
