enum EClassID
{
	NeutralMinionCamp = 0,
	FollowerObject = 1,
	FollowerObjectWithLerpMovement = 2,
	AIHeroClient = 3,
	AIMarker = 4,
	AIMinionClient = 5,
	LevelPropAIClient = 6,
	AITurretClient = 7,
	AITurretCommon = 8,
	obj_GeneralParticleEmitter = 9,
	GameObject = 10,
	MissileClient = 11,
	DrawFX = 12,
	UnrevealedTarget = 13,
	BarracksDampener = 14,
	Barracks = 15,
	AnimatedBuilding = 16,
	BuildingClient = 17,
	obj_Lake = 18,
	obj_Levelsizer = 19,
	obj_NavPoint = 20,
	obj_SpawnPoint = 21,
	obj_LampBulb = 22,
	GrassObject = 23,
	HQ = 24,
	obj_InfoPoint = 25,
	LevelPropGameObject = 26,
	LevelPropSpawnerPoint = 27,
	Shop = 28,
	obj_Turret = 29,
};