enum ECharacterRecordParameter
{
	ATTACK_DELAY_CASTOFFSETPRECENT = 0,
	BASE_PHYSICAL_DAMAGE = 1,
	DAMAGE_PER_LEVEL = 2,
	ABILITY_SLOT_0_CC = 3,
	ABILITY_SLOT_1_CC = 4,
	ABILITY_SLOT_2_CC = 5,
	ABILITY_SLOT_3_CC = 6,
	SKILL_ORDER = 7,
	FIRST_ITEM = 8,
};