enum EGameDifficultyType
{
	GAME_DIFFICULTY_NEWBIE = 0,
	GAME_DIFFICULTY_INTERMEDIATE = 1,
	GAME_DIFFICULTY_ADVANCED = 2,
	GAME_DIFFICULTY_UBER = 3,
	GAME_DIFFICULTY_TUTORIAL = 4,
	GAME_DIFFICULTY_INTRO = 5,
};